### ISSUE TITLE
We can't use this library with the microsoft AddDbContextCheck

### ISSUE THREAD

**Issue by bhugot** [YounitedCredit/Younited.HealthCheck.EntityFrameworkMigrations#1]
When the dbcontext configuration is set to scoped then you can't have both working as same dbcontext is used and so as healthcheck are execute in parallel task it's  throwing errors.

The fix is to create a scope when creating the context.

There is an issue on AspNetCore repository https://github.com/dotnet/aspnetcore/issues/14453

**Comment by GuillaumeGuerra** [comment]
Thanks !
